"""centroid_tracker — frame-differenced centroid track (standalone template pair).

The math is the simplest real tracker in the suite's family — the sandbox preset behind
:class:`gottlux.detectors.flutter.SingleCentroidDetector` (strongest blob + EMA-smoothed
centroid), with the static background removed by **frame differencing** instead of the
suite's statistical background model: accumulate a count frame per step, subtract the
previous frame, threshold the increase, take the strongest connected component's centroid,
and EMA-smooth it into one track. Python uses ``scipy.ndimage.label`` for the components;
the MATLAB port (kept toolbox-free) uses the thresholded-diff *weighted* centroid instead
of connected components — noted in its header.
"""
from __future__ import annotations

from gottlux.export_tools import M_LOADER, PY_LOADER, ExportTool  # noqa: F401  (registry wiring)

PY = '''\
#!/usr/bin/env python3
# =====================================================================================
# run_centroid_tracker.py - frame-differenced single-target centroid track.
# Generated by GottLUX {version} on {stamp} from '{source}'.
#
# Ported (simplified) from the sandbox preset behind gottlux's 'single_centroid' detector
# (gottlux/detectors/flutter.py SingleCentroidDetector): per ACCUM_DT_S step, accumulate a
# count frame, DIFFERENCE it against the previous frame (static background cancels),
# threshold the increase, label connected components (scipy.ndimage), take the strongest
# component's centroid, and EMA-smooth it into one track. Omitted vs gottlux: the
# statistical background model, multi-target association, FFT annotation.
#
# Self-contained: numpy + scipy + h5py; matplotlib OPTIONAL (path PNG skipped without it).
# Run:   python run_centroid_tracker.py [events.h5]    (default input: data.h5 here)
# Out:   centroid_track.csv - columns t_s, cx_px, cy_px, area_px
#        centroid_track.png - the track over the sensor (only if matplotlib is present)
# =====================================================================================
import os
import sys

import numpy as np
from scipy import ndimage

# ----------------------------- baked parameters (edit freely) ------------------------
ACCUM_DT_S  = {accum_dt}     # step / frame accumulation window (s)
DIFF_THRESH = 0.5            # events/pixel of frame-to-frame INCREASE to call a pixel active
MIN_PIXELS  = 10             # smallest connected component worth tracking
SMOOTH      = 0.5            # EMA factor (0 = raw centroid, closer to 1 = stickier)

{loader}

def main():
    path = input_path()
    x, y, p, t_s, W, H = load_events(path)
    print("loaded %s: %d events, %dx%d px, %.3f s"
          % (os.path.basename(path), t_s.size, W, H, t_s[-1] if t_s.size else 0.0))
    if t_s.size < 16:
        print("too few events - nothing to do")
        return 0

    rows = []
    pos = None
    prev = np.zeros((H, W), np.float64)
    steps = np.arange(float(t_s[0]) + ACCUM_DT_S, float(t_s[-1]), ACCUM_DT_S)
    for ct in steps:
        lo = np.searchsorted(t_s, ct - ACCUM_DT_S)
        hi = np.searchsorted(t_s, ct)
        flat = y[lo:hi] * W + x[lo:hi]
        frame = np.bincount(flat, minlength=H * W).reshape(H, W).astype(np.float64)
        active = (frame - prev) > DIFF_THRESH          # frame differencing: statics cancel
        prev = frame
        labels, n_lab = ndimage.label(active)
        if n_lab == 0:
            continue
        sizes = ndimage.sum_labels(active, labels, index=np.arange(1, n_lab + 1))
        best = int(np.argmax(sizes)) + 1
        if sizes[best - 1] < MIN_PIXELS:
            continue
        cy, cx = ndimage.center_of_mass(active, labels, best)
        if pos is not None:                            # EMA smoothing (the sandbox preset)
            cx = SMOOTH * pos[0] + (1 - SMOOTH) * cx
            cy = SMOOTH * pos[1] + (1 - SMOOTH) * cy
        pos = (cx, cy)
        rows.append((ct, cx, cy, float(sizes[best - 1])))

    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "centroid_track.csv")
    with open(out, "w", encoding="utf-8") as f:
        f.write("t_s,cx_px,cy_px,area_px\\n")
        for (ct, cx, cy, area) in rows:
            f.write("%.6f,%.2f,%.2f,%.0f\\n" % (ct, cx, cy, area))
    print("wrote %s  (tracked %d / %d steps)" % (out, len(rows), steps.size))

    plt = try_pyplot()
    if plt is not None and rows:
        arr = np.array([(r[1], r[2]) for r in rows])
        fig, ax = plt.subplots(figsize=(6, 6 * H / max(W, 1)))
        ax.plot(arr[:, 0], arr[:, 1], "-o", ms=2.5, lw=0.9)
        ax.set_xlim(0, W)
        ax.set_ylim(H, 0)                              # image convention: y down
        ax.set_xlabel("x (px)")
        ax.set_ylabel("y (px)")
        ax.set_title("centroid track (%d steps of %g s)" % (len(rows), ACCUM_DT_S))
        fig.savefig(os.path.join(here, "centroid_track.png"), dpi=150,
                    bbox_inches="tight")
        print("wrote centroid_track.png")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

M = '''\
% =====================================================================================
% run_centroid_tracker.m - frame-differenced single-target centroid track.
% Generated by GottLUX {version} on {stamp} from '{source}'.
%
% Ported (simplified) from the sandbox preset behind gottlux's 'single_centroid' detector.
% NOTE: to stay toolbox-free this MATLAB port uses the WEIGHTED CENTROID of all pixels
% whose count increased past DIFF_THRESH (no connected-component labeling, which would
% need the Image Processing Toolbox); the Python twin labels components with scipy.
% Run:   open in MATLAB and press Run (or:  >> run_centroid_tracker)
% Out:   centroid_track.csv - columns t_s, cx_px, cy_px, n_active_px;  plus a path figure
% =====================================================================================

% ----------------------------- baked parameters (edit freely) ------------------------
DATA_FILE   = 'data.h5';     % or set an absolute path to any GottLUX-exported .h5
ACCUM_DT_S  = {accum_dt};    % step / frame accumulation window (s)
DIFF_THRESH = 0.5;           % events/pixel of frame-to-frame increase = an active pixel
MIN_PIXELS  = 10;            % smallest active-pixel count worth tracking
SMOOTH      = 0.5;           % EMA factor (0 = raw centroid, closer to 1 = stickier)

[x, y, p, t_s, W, H] = gl_load_events(DATA_FILE);
fprintf('loaded %s: %d events, %dx%d px, %.3f s\\n', DATA_FILE, numel(t_s), W, H, t_s(end));

steps = (t_s(1) + ACCUM_DT_S):ACCUM_DT_S:t_s(end);
track = zeros(0, 4);
pos = [NaN, NaN];
prev = zeros(H, W);
for si = 1:numel(steps)
    ct = steps(si);
    m = t_s >= (ct - ACCUM_DT_S) & t_s < ct;
    frame = accumarray([y(m) + 1, x(m) + 1], 1, [H, W]);
    diff_im = frame - prev;
    prev = frame;
    active = diff_im > DIFF_THRESH;                  % frame differencing: statics cancel
    n_active = sum(active(:));
    if n_active < MIN_PIXELS
        continue
    end
    [ay, ax] = find(active);
    wgt = diff_im(active);                           % weight by the count increase
    cx = sum((ax - 1) .* wgt) / sum(wgt);
    cy = sum((ay - 1) .* wgt) / sum(wgt);
    if isfinite(pos(1))
        cx = SMOOTH * pos(1) + (1 - SMOOTH) * cx;    % EMA smoothing (the sandbox preset)
        cy = SMOOTH * pos(2) + (1 - SMOOTH) * cy;
    end
    pos = [cx, cy];
    track(end + 1, :) = [ct, cx, cy, n_active];      %#ok<SAGROW>
end

writematrix(track, 'centroid_track.csv');
fprintf('wrote centroid_track.csv (tracked %d / %d steps)\\n', size(track, 1), numel(steps));
figure;
plot(track(:, 2), track(:, 3), '-o', 'MarkerSize', 3);
axis([0, W, 0, H]);
set(gca, 'YDir', 'reverse');                         % image convention: y down
xlabel('x (px)');
ylabel('y (px)');
title(sprintf('centroid track (%d steps of %g s)', size(track, 1), ACCUM_DT_S));
grid on;

{loader}
'''

TOOL = ExportTool(
    name="centroid_tracker",
    description="frame-differenced single-target centroid track (the simplest real tracker)",
    module="gottlux/detectors/flutter.py (SingleCentroidDetector's sandbox preset, "
           "background model replaced by frame differencing)",
    outputs=(("centroid_track.csv", "columns t_s, cx_px, cy_px, area/active px"),
             ("centroid_track.png / a MATLAB figure", "the track over the sensor")),
    params=(("accum_dt", "step / frame accumulation window (s)"),),
    py_template=PY,
    m_template=M,
)
