"""event_frames — accumulate event-count frames over a window (standalone template pair).

The math is the ``mode="count"`` path of :func:`gottlux.core.accumulate.accumulate_frame`,
applied per time step: one ``(H, W)`` histogram of event positions per ``ACCUM_DT_S``
window. That is the primitive every viewer/detector in the suite renders first.
"""
from __future__ import annotations

from gottlux.export_tools import M_LOADER, PY_LOADER, ExportTool  # noqa: F401  (registry wiring)

PY = '''\
#!/usr/bin/env python3
# =====================================================================================
# run_event_frames.py - accumulate event-count frames from a GottLUX HDF5 event file.
# Generated by GottLUX {version} on {stamp} from '{source}'.
#
# Ported (simplified) from gottlux/core/accumulate.py accumulate_frame(mode="count"):
# each frame is a per-pixel count of the events inside one ACCUM_DT_S window.
#
# Self-contained: numpy + h5py only; matplotlib OPTIONAL (preview PNG skipped without it).
# Run:   python run_event_frames.py [events.h5]        (default input: data.h5 here)
# Out:   event_frames.npz  - frames (n, H, W) uint32, t_edges_s (n+1,) float
#        event_frames_preview.png  - the densest frame (only if matplotlib is present)
# =====================================================================================
import os
import sys

import numpy as np

# ----------------------------- baked parameters (edit freely) ------------------------
ACCUM_DT_S = {accum_dt}      # accumulation window per frame (s)
MAX_FRAMES = {max_frames}    # safety cap on the number of frames kept

{loader}

def main():
    path = input_path()
    x, y, p, t_s, W, H = load_events(path)
    print("loaded %s: %d events, %dx%d px, %.3f s"
          % (os.path.basename(path), t_s.size, W, H, t_s[-1] if t_s.size else 0.0))
    if t_s.size == 0:
        print("no events - nothing to do")
        return 0

    # frame index per event, then one bincount over (frame, y, x) does all frames at once
    k = np.floor(t_s / ACCUM_DT_S).astype(np.int64)
    n = int(k.max()) + 1
    if n > MAX_FRAMES:
        print("capping %d frames to MAX_FRAMES=%d (raise it or grow ACCUM_DT_S)"
              % (n, MAX_FRAMES))
        keep = k < MAX_FRAMES
        x, y, k = x[keep], y[keep], k[keep]
        n = MAX_FRAMES
    flat = (k * H + y) * W + x
    frames = np.bincount(flat, minlength=n * H * W).reshape(n, H, W).astype(np.uint32)
    t_edges = np.arange(n + 1) * ACCUM_DT_S

    out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "event_frames.npz")
    np.savez_compressed(out, frames=frames, t_edges_s=t_edges)
    dens = int(np.argmax(frames.reshape(n, -1).sum(axis=1)))
    print("wrote %s  (%d frames of %dx%d; densest at t=%.3f s)"
          % (out, n, H, W, (dens + 0.5) * ACCUM_DT_S))

    plt = try_pyplot()
    if plt is not None:
        fig, ax = plt.subplots(figsize=(6, 6 * H / max(W, 1)))
        ax.imshow(frames[dens], cmap="inferno", origin="upper")
        ax.set_title("event count, t = %.3f s (dt = %g s)" % ((dens + 0.5) * ACCUM_DT_S,
                                                              ACCUM_DT_S))
        fig.savefig(os.path.join(os.path.dirname(out), "event_frames_preview.png"),
                    dpi=150, bbox_inches="tight")
        print("wrote event_frames_preview.png")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

M = '''\
% =====================================================================================
% run_event_frames.m - accumulate event-count frames from a GottLUX HDF5 event file.
% Generated by GottLUX {version} on {stamp} from '{source}'.
%
% Ported (simplified) from gottlux/core/accumulate.py accumulate_frame(mode="count").
% Base MATLAB only (h5read); works on any GottLUX-exported .h5.
% Run:   open in MATLAB and press Run (or:  >> run_event_frames)
% Out:   event_frames.mat  - frames (H, W, n), t_edges_s (n+1,)
%        a figure showing the densest frame
% =====================================================================================

% ----------------------------- baked parameters (edit freely) ------------------------
DATA_FILE  = 'data.h5';      % or set an absolute path to any GottLUX-exported .h5
ACCUM_DT_S = {accum_dt};     % accumulation window per frame (s)
MAX_FRAMES = {max_frames};   % safety cap on the number of frames kept

[x, y, p, t_s, W, H] = gl_load_events(DATA_FILE);
fprintf('loaded %s: %d events, %dx%d px, %.3f s\\n', DATA_FILE, numel(t_s), W, H, t_s(end));

k = floor(t_s / ACCUM_DT_S);                       % frame index per event (0-based)
n = min(max(k) + 1, MAX_FRAMES);
keep = k < n;
xk = x(keep); yk = y(keep); kk = k(keep);
% one accumarray over (y, x, frame) builds every frame at once (MATLAB is 1-based)
frames = accumarray([yk + 1, xk + 1, kk + 1], 1, [H, W, n]);
t_edges_s = (0:n) * ACCUM_DT_S;
save('event_frames.mat', 'frames', 't_edges_s');

per_frame = squeeze(sum(sum(frames, 1), 2));
[~, dens] = max(per_frame);
fprintf('wrote event_frames.mat (%d frames of %dx%d; densest at t=%.3f s)\\n', ...
        n, H, W, (dens - 0.5) * ACCUM_DT_S);
figure;
imagesc(frames(:, :, dens));
axis image;
colormap hot;
colorbar;
title(sprintf('event count, t = %.3f s (dt = %g s)', (dens - 0.5) * ACCUM_DT_S, ACCUM_DT_S));

{loader}
'''

TOOL = ExportTool(
    name="event_frames",
    description="accumulate per-pixel event-count frames over a chosen window",
    module="gottlux/core/accumulate.py (accumulate_frame, mode='count')",
    outputs=(("event_frames.npz / event_frames.mat", "the (n, H, W) frame stack + bin edges"),
             ("event_frames_preview.png", "the densest frame (Python, if matplotlib present)")),
    params=(("accum_dt", "accumulation window per frame (s)"),
            ("max_frames", "safety cap on the number of frames kept")),
    py_template=PY,
    m_template=M,
)
