"""event_rate — the event-rate-vs-time curve (standalone template pair).

The math is :meth:`gottlux.io.recording.Recording.event_rate`: a histogram of event times
divided by the bin width. It is the first plot every gottlux run makes (the ``overview``
analysis) — the single fastest way to see when a recording is interesting.
"""
from __future__ import annotations

from gottlux.export_tools import M_LOADER, PY_LOADER, ExportTool  # noqa: F401  (registry wiring)

PY = '''\
#!/usr/bin/env python3
# =====================================================================================
# run_event_rate.py - event-rate-vs-time curve from a GottLUX HDF5 event file.
# Generated by GottLUX {version} on {stamp} from '{source}'.
#
# Ported from gottlux/io/recording.py Recording.event_rate: rate[k] = histogram of event
# times / bin width. The suite's 'overview' analysis draws exactly this curve.
#
# Self-contained: numpy + h5py only; matplotlib OPTIONAL (the PNG is skipped without it).
# Run:   python run_event_rate.py [events.h5]          (default input: data.h5 here)
# Out:   event_rate.csv  - columns t_s, rate_hz
#        event_rate.png  - the curve (only if matplotlib is present)
# =====================================================================================
import os
import sys

import numpy as np

# ----------------------------- baked parameters (edit freely) ------------------------
BIN_S = {rate_bin}           # rate histogram bin (s); smaller = finer, noisier

{loader}

def main():
    path = input_path()
    x, y, p, t_s, W, H = load_events(path)
    print("loaded %s: %d events, %dx%d px, %.3f s"
          % (os.path.basename(path), t_s.size, W, H, t_s[-1] if t_s.size else 0.0))
    if t_s.size == 0:
        print("no events - nothing to do")
        return 0

    edges = np.arange(0.0, t_s[-1] + BIN_S, BIN_S)
    counts = np.histogram(t_s, bins=edges)[0]
    centers = 0.5 * (edges[:-1] + edges[1:])
    rate_hz = counts / BIN_S

    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, "event_rate.csv")
    with open(out, "w", encoding="utf-8") as f:
        f.write("t_s,rate_hz\\n")
        for i in range(centers.size):
            f.write("%.6f,%.1f\\n" % (centers[i], rate_hz[i]))
    print("wrote %s  (%d bins of %g s; mean %.0f ev/s, peak %.0f ev/s)"
          % (out, centers.size, BIN_S, rate_hz.mean(), rate_hz.max()))

    plt = try_pyplot()
    if plt is not None:
        fig, ax = plt.subplots(figsize=(8, 3))
        ax.plot(centers, rate_hz, lw=0.9)
        ax.set_xlabel("time (s)")
        ax.set_ylabel("event rate (ev/s)")
        ax.set_title("event rate - %s" % os.path.basename(path))
        fig.savefig(os.path.join(here, "event_rate.png"), dpi=150, bbox_inches="tight")
        print("wrote event_rate.png")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

M = '''\
% =====================================================================================
% run_event_rate.m - event-rate-vs-time curve from a GottLUX HDF5 event file.
% Generated by GottLUX {version} on {stamp} from '{source}'.
%
% Ported from gottlux/io/recording.py Recording.event_rate. Base MATLAB only (h5read).
% Run:   open in MATLAB and press Run (or:  >> run_event_rate)
% Out:   event_rate.csv  - columns t_s, rate_hz;  plus the curve as a figure
% =====================================================================================

% ----------------------------- baked parameters (edit freely) ------------------------
DATA_FILE = 'data.h5';       % or set an absolute path to any GottLUX-exported .h5
BIN_S     = {rate_bin};      % rate histogram bin (s); smaller = finer, noisier

[x, y, p, t_s, W, H] = gl_load_events(DATA_FILE);
fprintf('loaded %s: %d events, %dx%d px, %.3f s\\n', DATA_FILE, numel(t_s), W, H, t_s(end));

edges = 0:BIN_S:(t_s(end) + BIN_S);
counts = histcounts(t_s, edges);
centers = 0.5 * (edges(1:end-1) + edges(2:end));
rate_hz = counts / BIN_S;

writematrix([centers(:), rate_hz(:)], 'event_rate.csv');
fprintf('wrote event_rate.csv (%d bins of %g s; mean %.0f ev/s, peak %.0f ev/s)\\n', ...
        numel(centers), BIN_S, mean(rate_hz), max(rate_hz));

figure;
plot(centers, rate_hz);
xlabel('time (s)');
ylabel('event rate (ev/s)');
title('event rate');
grid on;

{loader}
'''

TOOL = ExportTool(
    name="event_rate",
    description="the event-rate-vs-time curve (+ plot) — when is the recording busy?",
    module="gottlux/io/recording.py (Recording.event_rate)",
    outputs=(("event_rate.csv", "columns t_s, rate_hz"),
             ("event_rate.png / a MATLAB figure", "the rate curve")),
    params=(("rate_bin", "rate histogram bin (s)"),),
    py_template=PY,
    m_template=M,
)
