"""flicker_map — per-cell dominant flicker frequency map (standalone template pair).

The math is a single-window port of :func:`gottlux.core.frequency.flicker_map`: bin the
sensor into ``CELL_PX``-square cells, build every cell's event-count time series in one
pass, FFT all cells at once, and keep each cell's in-band peak frequency + SNR. Omitted
honestly: the whole-recording best-window tiling of ``flicker_map_max`` (this analyzes one
window) and the automatic memory-budget coarsening (a simple cap is kept).
"""
from __future__ import annotations

from gottlux.export_tools import M_LOADER, PY_LOADER, ExportTool  # noqa: F401  (registry wiring)

PY = '''\
#!/usr/bin/env python3
# =====================================================================================
# run_flicker_map.py - per-cell dominant flicker-frequency map from a GottLUX HDF5 file.
# Generated by GottLUX {version} on {stamp} from '{source}'.
#
# Ported (simplified) from gottlux/core/frequency.py flicker_map: the sensor is split into
# CELL_PX-square cells; each cell's event-count time series (binned at FS_HZ) is FFT'd -
# all cells in one vectorized rfft - and the in-band peak frequency + SNR are kept per
# cell. A rotor disk literally lights up at its blade-pass frequency while the static
# background stays dark. Omitted vs gottlux: best-of-many-windows tiling (flicker_map_max)
# and auto memory-budget fs coarsening.
#
# Self-contained: numpy + h5py only; matplotlib OPTIONAL (the PNG is skipped without it).
# Run:   python run_flicker_map.py [events.h5]         (default input: data.h5 here)
# Out:   flicker_map.npz  - dominant_freq_hz (Gh, Gw; NaN = quiet), snr, event_count
#        flicker_map.png  - the map, frequency as color (only if matplotlib is present)
# =====================================================================================
import os
import sys

import numpy as np

# ----------------------------- baked parameters (edit freely) ------------------------
CELL_PX     = {cell}         # spatial cell size (px); smaller = finer map, more cells
FS_HZ       = {fs}           # binning sample rate (must exceed 2 x FREQ_HI_HZ)
FREQ_LO_HZ  = {freq_lo}      # band searched for each cell's dominant line
FREQ_HI_HZ  = {freq_hi}
MIN_EVENTS  = 40             # cells with fewer events are left NaN (too quiet to judge)
MAX_ELEMS   = 200000000      # cap on cells x time-bins (guards RAM on long recordings)

{loader}

def main():
    path = input_path()
    x, y, p, t_s, W, H = load_events(path)
    print("loaded %s: %d events, %dx%d px, %.3f s"
          % (os.path.basename(path), t_s.size, W, H, t_s[-1] if t_s.size else 0.0))
    Gw = (W + CELL_PX - 1) // CELL_PX
    Gh = (H + CELL_PX - 1) // CELL_PX
    out_freq = np.full((Gh, Gw), np.nan, np.float32)
    out_snr = np.zeros((Gh, Gw), np.float32)
    if t_s.size < 8:
        print("too few events - nothing to do")
        return 0

    # --- one pass: per-cell event-count time series (cells x time-bins count matrix)
    span = max(float(t_s[-1] - t_s[0]), 1e-9)
    fs = FS_HZ
    n_tbins = int(span * fs)
    if Gw * Gh * n_tbins > MAX_ELEMS and n_tbins > 0:
        fs = max(fs * MAX_ELEMS / (Gw * Gh * n_tbins), 2.2 * FREQ_HI_HZ)
        n_tbins = int(span * fs)
        print("coarsened fs to %.0f Hz to fit MAX_ELEMS" % fs)
    if n_tbins < 8:
        print("window too short - nothing to do")
        return 0
    tb = np.clip(((t_s - t_s[0]) * fs).astype(np.int64), 0, n_tbins - 1)
    cix = np.clip(x // CELL_PX, 0, Gw - 1)
    ciy = np.clip(y // CELL_PX, 0, Gh - 1)
    cell_idx = ciy * Gw + cix
    counts = np.bincount(cell_idx * n_tbins + tb,
                         minlength=Gh * Gw * n_tbins).reshape(Gh * Gw, n_tbins)
    cell_counts = counts.sum(axis=1)

    # --- FFT every sufficiently-active cell at once
    active = np.where(cell_counts >= MIN_EVENTS)[0]
    if active.size:
        sig = counts[active].astype(np.float64)
        sig -= sig.mean(axis=1, keepdims=True)
        sig *= (np.hanning(n_tbins) if n_tbins > 1 else np.ones(n_tbins))[None, :]
        spec = np.abs(np.fft.rfft(sig, axis=1)) / n_tbins
        if spec.shape[1] > 2:
            spec[:, 1:-1] *= 2.0
        power = spec ** 2
        freqs = np.fft.rfftfreq(n_tbins, d=1.0 / fs)
        band = (freqs >= FREQ_LO_HZ) & (freqs <= FREQ_HI_HZ)
        if band.any():
            bpow = power[:, band]
            bi = np.argmax(bpow, axis=1)
            rows = np.arange(active.size)
            peak_power = bpow[rows, bi]
            noise = np.median(power[:, 1:], axis=1) + 1e-12
            ay = active // Gw
            ax = active % Gw
            out_freq[ay, ax] = freqs[band][bi].astype(np.float32)
            out_snr[ay, ax] = (peak_power / noise).astype(np.float32)

    here = os.path.dirname(os.path.abspath(__file__))
    np.savez_compressed(os.path.join(here, "flicker_map.npz"),
                        dominant_freq_hz=out_freq, snr=out_snr,
                        event_count=cell_counts.reshape(Gh, Gw))
    valid = np.isfinite(out_freq)
    if valid.any():
        k = int(np.nanargmax(np.where(valid, out_snr, -1)))
        ky, kx = k // Gw, k % Gw
        print("wrote flicker_map.npz  (%d/%d active cells; strongest %.0f Hz "
              "at cell (%d,%d), SNR %.1f)"
              % (int(valid.sum()), Gh * Gw, out_freq[ky, kx], kx, ky, out_snr[ky, kx]))
    else:
        print("wrote flicker_map.npz  (no cell passed MIN_EVENTS=%d)" % MIN_EVENTS)

    plt = try_pyplot()
    if plt is not None:
        fig, ax = plt.subplots(figsize=(6.4, 6.4 * Gh / max(Gw, 1)))
        im = ax.imshow(out_freq, cmap="turbo", origin="upper",
                       vmin=FREQ_LO_HZ, vmax=FREQ_HI_HZ)
        fig.colorbar(im, ax=ax, label="dominant frequency (Hz)")
        ax.set_title("flicker map (%g px cells, %g-%g Hz)"
                     % (CELL_PX, FREQ_LO_HZ, FREQ_HI_HZ))
        fig.savefig(os.path.join(here, "flicker_map.png"), dpi=150, bbox_inches="tight")
        print("wrote flicker_map.png")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

M = '''\
% =====================================================================================
% run_flicker_map.m - per-cell dominant flicker-frequency map from a GottLUX HDF5 file.
% Generated by GottLUX {version} on {stamp} from '{source}'.
%
% Ported (simplified) from gottlux/core/frequency.py flicker_map; base MATLAB only.
% Run:   open in MATLAB and press Run (or:  >> run_flicker_map)
% Out:   flicker_map.mat - dominant_freq_hz (Gh x Gw; NaN = quiet), snr, event_count
%        a figure showing the map (frequency as color)
% =====================================================================================

% ----------------------------- baked parameters (edit freely) ------------------------
DATA_FILE   = 'data.h5';     % or set an absolute path to any GottLUX-exported .h5
CELL_PX     = {cell};        % spatial cell size (px)
FS_HZ       = {fs};          % binning sample rate (must exceed 2 x FREQ_HI_HZ)
FREQ_LO_HZ  = {freq_lo};     % band searched for each cell's dominant line
FREQ_HI_HZ  = {freq_hi};
MIN_EVENTS  = 40;            % cells with fewer events stay NaN

[x, y, p, t_s, W, H] = gl_load_events(DATA_FILE);
fprintf('loaded %s: %d events, %dx%d px, %.3f s\\n', DATA_FILE, numel(t_s), W, H, t_s(end));
Gw = ceil(W / CELL_PX);
Gh = ceil(H / CELL_PX);
span = max(t_s(end) - t_s(1), 1e-9);
n_tbins = floor(span * FS_HZ);

% --- one pass: per-cell event-count time series ((Gh*Gw) x n_tbins count matrix)
tb = min(floor((t_s - t_s(1)) * FS_HZ), n_tbins - 1);
cix = min(floor(x / CELL_PX), Gw - 1);
ciy = min(floor(y / CELL_PX), Gh - 1);
cell_idx = ciy * Gw + cix;                          % 0-based flat cell index
counts = accumarray([cell_idx + 1, tb + 1], 1, [Gh * Gw, n_tbins]);
event_count = reshape(sum(counts, 2), [Gw, Gh])';   % note: reshape is column-major

% --- FFT every sufficiently-active cell at once
dominant_freq_hz = nan(Gh, Gw);
snr = zeros(Gh, Gw);
active = find(sum(counts, 2) >= MIN_EVENTS);
if ~isempty(active)
    sig = counts(active, :);
    sig = sig - mean(sig, 2);
    hann_win = 0.5 * (1 - cos(2 * pi * (0:n_tbins-1) / max(n_tbins - 1, 1)));
    sig = sig .* hann_win;
    spec = abs(fft(sig, [], 2)) / n_tbins;
    half = floor(n_tbins / 2) + 1;
    spec = spec(:, 1:half);
    spec(:, 2:end-1) = spec(:, 2:end-1) * 2.0;
    power = spec .^ 2;
    freqs = (0:half-1) * (FS_HZ / n_tbins);
    band = freqs >= FREQ_LO_HZ & freqs <= FREQ_HI_HZ;
    bpow = power(:, band);
    bfreq = freqs(band);
    [peak_power, bi] = max(bpow, [], 2);
    noise = median(power(:, 2:end), 2) + 1e-12;
    ay = floor((active - 1) / Gw) + 1;              % back to (row, col) in the cell grid
    ax = mod(active - 1, Gw) + 1;
    for k = 1:numel(active)
        dominant_freq_hz(ay(k), ax(k)) = bfreq(bi(k));
        snr(ay(k), ax(k)) = peak_power(k) / noise(k);
    end
end

save('flicker_map.mat', 'dominant_freq_hz', 'snr', 'event_count');
[best_snr, k] = max(snr(:));
fprintf('wrote flicker_map.mat (%d active cells; strongest %.0f Hz, SNR %.1f)\\n', ...
        sum(isfinite(dominant_freq_hz(:))), dominant_freq_hz(k), best_snr);
figure;
imagesc(dominant_freq_hz, [FREQ_LO_HZ, FREQ_HI_HZ]);
axis image;
colormap turbo;
colorbar;
title(sprintf('flicker map (%g px cells, %g-%g Hz)', CELL_PX, FREQ_LO_HZ, FREQ_HI_HZ));

{loader}
'''

TOOL = ExportTool(
    name="flicker_map",
    description="per-cell dominant flicker-frequency map — where is it flickering, how fast?",
    module="gottlux/core/frequency.py (flicker_map — single window, no best-window tiling)",
    outputs=(("flicker_map.npz / flicker_map.mat",
              "dominant_freq_hz (NaN = quiet), snr, event_count per cell"),
             ("flicker_map.png / a MATLAB figure", "the map, frequency as color")),
    params=(("cell", "spatial cell size (px)"),
            ("fs", "binning sample rate (Hz)"),
            ("freq_lo", "band low edge (Hz)"),
            ("freq_hi", "band high edge (Hz)")),
    py_template=PY,
    m_template=M,
)
