"""region_spectrum — windowed ROI event-time FFT: peak frequency + SNR (template pair).

The math is the essential core of :func:`gottlux.core.frequency.region_spectrum`: bin the
region's event times to a regular series at ``fs``, mean-subtract, Hann-window, FFT,
one-sided amplitude correction, then the in-band peak and its SNR against a robust median
noise floor. Omitted honestly: whitening, the harmonic-comb score, and the de-rotation
high-pass — the gottlux original has them; this port keeps the headline peak/SNR readout.
"""
from __future__ import annotations

from gottlux.export_tools import M_LOADER, PY_LOADER, ExportTool  # noqa: F401  (registry wiring)

PY = '''\
#!/usr/bin/env python3
# =====================================================================================
# run_region_spectrum.py - ROI event-time power spectrum (peak flutter frequency + SNR).
# Generated by GottLUX {version} on {stamp} from '{source}'.
#
# Ported (simplified) from gottlux/core/frequency.py region_spectrum: bin the ROI's event
# times to a regular count series at FS_HZ, mean-subtract, Hann-window, FFT, one-sided
# amplitude correction; the in-band peak and its SNR = peak power / median(power[1:]).
# Omitted vs gottlux: whitening, the harmonic-comb score, rotation de-trending.
#
# Self-contained: numpy + h5py only; matplotlib OPTIONAL (the PNG is skipped without it).
# Run:   python run_region_spectrum.py [events.h5]     (default input: data.h5 here)
# Out:   region_spectrum.csv   - columns freq_hz, power
#        region_spectrum.json  - peak_hz, snr, band, n_events
#        region_spectrum.png   - the spectrum (only if matplotlib is present)
# =====================================================================================
import json
import os
import sys

import numpy as np

# ----------------------------- baked parameters (edit freely) ------------------------
FS_HZ      = {fs}            # binning sample rate (must exceed 2 x FREQ_HI_HZ)
FREQ_LO_HZ = {freq_lo}       # flutter band searched for the dominant line
FREQ_HI_HZ = {freq_hi}
ROI        = ({roi_x0}, {roi_y0}, {roi_x1}, {roi_y1})   # (x0, y0, x1, y1) px, x1/y1 exclusive

{loader}

def main():
    path = input_path()
    x, y, p, t_s, W, H = load_events(path)
    print("loaded %s: %d events, %dx%d px, %.3f s"
          % (os.path.basename(path), t_s.size, W, H, t_s[-1] if t_s.size else 0.0))
    x0, y0, x1, y1 = ROI
    m = (x >= x0) & (x < x1) & (y >= y0) & (y < y1)
    t = t_s[m]
    print("ROI (%d,%d)-(%d,%d): %d events" % (x0, y0, x1, y1, t.size))
    if t.size < 8:
        print("too few events in the ROI - nothing to do")
        return 0

    # --- bin the event times into a regular count series at FS_HZ (frequency.bin_signal)
    dt = 1.0 / FS_HZ
    n = int((t[-1] - t[0]) / dt)
    if n < 8:
        print("window too short at FS_HZ=%g - nothing to do" % FS_HZ)
        return 0
    edges = t[0] + np.arange(n + 1) * dt
    sig = np.histogram(t, bins=edges)[0].astype(np.float64)

    # --- mean-subtract, Hann window, FFT, one-sided amplitude correction, power
    sig = sig - sig.mean()
    sig = sig * (np.hanning(n) if n > 1 else np.ones(n))
    spec = np.abs(np.fft.rfft(sig)) / n
    if spec.size > 2:
        spec[1:-1] = spec[1:-1] * 2.0
    power = spec ** 2
    freqs = np.fft.rfftfreq(n, d=dt)

    # --- the in-band peak and its SNR against the robust (median) noise floor
    band = (freqs >= FREQ_LO_HZ) & (freqs <= FREQ_HI_HZ)
    if not band.any():
        print("no FFT bins inside the band %g-%g Hz" % (FREQ_LO_HZ, FREQ_HI_HZ))
        return 0
    bi = int(np.argmax(power[band]))
    peak_hz = float(freqs[band][bi])
    peak_power = float(power[band][bi])
    noise = float(np.median(power[1:])) if power.size > 1 else 0.0
    snr = peak_power / (noise + 1e-12)
    print("in-band peak: %.1f Hz  (SNR %.1f over %g-%g Hz)"
          % (peak_hz, snr, FREQ_LO_HZ, FREQ_HI_HZ))

    here = os.path.dirname(os.path.abspath(__file__))
    with open(os.path.join(here, "region_spectrum.csv"), "w", encoding="utf-8") as f:
        f.write("freq_hz,power\\n")
        for i in range(freqs.size):
            f.write("%.4f,%.8g\\n" % (freqs[i], power[i]))
    result = dict(peak_hz=peak_hz, snr=snr, band_hz=[FREQ_LO_HZ, FREQ_HI_HZ],
                  roi=[x0, y0, x1, y1], fs_hz=FS_HZ, n_events=int(t.size))
    with open(os.path.join(here, "region_spectrum.json"), "w", encoding="utf-8") as f:
        json.dump(result, f, indent=2)
    print("wrote region_spectrum.csv + region_spectrum.json")

    plt = try_pyplot()
    if plt is not None:
        fig, ax = plt.subplots(figsize=(8, 3.2))
        ax.semilogy(freqs[1:], power[1:] + 1e-20, lw=0.9)
        ax.axvspan(FREQ_LO_HZ, FREQ_HI_HZ, alpha=0.12, color="tab:orange")
        ax.axvline(peak_hz, color="tab:red", lw=1.0, ls="--")
        ax.set_xlabel("frequency (Hz)")
        ax.set_ylabel("power")
        ax.set_title("ROI spectrum - peak %.1f Hz, SNR %.1f" % (peak_hz, snr))
        fig.savefig(os.path.join(here, "region_spectrum.png"), dpi=150,
                    bbox_inches="tight")
        print("wrote region_spectrum.png")
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

M = '''\
% =====================================================================================
% run_region_spectrum.m - ROI event-time power spectrum (peak flutter frequency + SNR).
% Generated by GottLUX {version} on {stamp} from '{source}'.
%
% Ported (simplified) from gottlux/core/frequency.py region_spectrum; base MATLAB only.
% Run:   open in MATLAB and press Run (or:  >> run_region_spectrum)
% Out:   region_spectrum.csv - columns freq_hz, power; peak/SNR printed + a figure
% =====================================================================================

% ----------------------------- baked parameters (edit freely) ------------------------
DATA_FILE  = 'data.h5';      % or set an absolute path to any GottLUX-exported .h5
FS_HZ      = {fs};           % binning sample rate (must exceed 2 x FREQ_HI_HZ)
FREQ_LO_HZ = {freq_lo};      % flutter band searched for the dominant line
FREQ_HI_HZ = {freq_hi};
ROI        = [{roi_x0}, {roi_y0}, {roi_x1}, {roi_y1}];   % [x0 y0 x1 y1] px, x1/y1 exclusive

[x, y, p, t_s, W, H] = gl_load_events(DATA_FILE);
fprintf('loaded %s: %d events, %dx%d px, %.3f s\\n', DATA_FILE, numel(t_s), W, H, t_s(end));
m = x >= ROI(1) & x < ROI(3) & y >= ROI(2) & y < ROI(4);
t = t_s(m);
fprintf('ROI (%d,%d)-(%d,%d): %d events\\n', ROI(1), ROI(2), ROI(3), ROI(4), numel(t));

% --- bin the event times into a regular count series at FS_HZ
dt = 1.0 / FS_HZ;
n = floor((t(end) - t(1)) / dt);
edges = t(1) + (0:n) * dt;
sig = histcounts(t, edges);
sig = sig - mean(sig);
hann_win = 0.5 * (1 - cos(2 * pi * (0:n-1) / max(n - 1, 1)));   % Hann, toolbox-free
sig = sig .* hann_win;

% --- FFT, one-sided amplitude correction, power
spec = abs(fft(sig)) / n;
half = floor(n / 2) + 1;
spec = spec(1:half);
if numel(spec) > 2
    spec(2:end-1) = spec(2:end-1) * 2.0;
end
power = spec .^ 2;
freqs = (0:half-1) * (FS_HZ / n);

% --- the in-band peak and its SNR against the robust (median) noise floor
band = freqs >= FREQ_LO_HZ & freqs <= FREQ_HI_HZ;
bpow = power(band);
bfreq = freqs(band);
[peak_power, bi] = max(bpow);
peak_hz = bfreq(bi);
noise = median(power(2:end));
snr = peak_power / (noise + 1e-12);
fprintf('in-band peak: %.1f Hz  (SNR %.1f over %g-%g Hz)\\n', ...
        peak_hz, snr, FREQ_LO_HZ, FREQ_HI_HZ);

writematrix([freqs(:), power(:)], 'region_spectrum.csv');
fprintf('wrote region_spectrum.csv\\n');
figure;
semilogy(freqs(2:end), power(2:end) + 1e-20);
xlabel('frequency (Hz)');
ylabel('power');
title(sprintf('ROI spectrum - peak %.1f Hz, SNR %.1f', peak_hz, snr));
grid on;

{loader}
'''

TOOL = ExportTool(
    name="region_spectrum",
    description="ROI event-time FFT: the dominant flutter frequency + its SNR",
    module="gottlux/core/frequency.py (region_spectrum — whitening/harmonics omitted)",
    outputs=(("region_spectrum.csv", "columns freq_hz, power"),
             ("region_spectrum.json", "peak_hz, snr, band, ROI (Python)"),
             ("region_spectrum.png / a MATLAB figure", "the spectrum")),
    params=(("fs", "binning sample rate (Hz)"),
            ("freq_lo", "band low edge (Hz)"),
            ("freq_hi", "band high edge (Hz)"),
            ("roi_x0", "ROI left (px)"), ("roi_y0", "ROI top (px)"),
            ("roi_x1", "ROI right, exclusive (px)"), ("roi_y1", "ROI bottom, exclusive (px)")),
    py_template=PY,
    m_template=M,
)
