"""viz_config — export the complete visualization configuration as runnable scripts.

The math is the display path every viewer in the suite runs per frame:
:func:`gottlux.core.accumulate.accumulate_frame` (``count`` or ``polarity``) followed by
:func:`gottlux.core.tonemap.compress` / :func:`~gottlux.core.tonemap.compress_signed`
(percentile white-point + monotone tone curve), then a colormap. The exported pair bakes
the export-time mode, colormap, tone curve, accumulation window, and view crop as plain
editable variables, so the exact configured view reproduces anywhere — the Python script
saves PNG frames at evenly spaced instants (plus an MP4 of the whole clip when ``imageio``
can encode one), the MATLAB twin renders the same accumulated frames with ``imagesc`` and
saves them via ``saveas``.
"""
from __future__ import annotations

from gottlux.export_tools import M_LOADER, PY_LOADER, ExportTool  # noqa: F401  (registry wiring)

#: matplotlib colormap name → its nearest base-MATLAB colormap (no toolboxes). The MATLAB
#: script receives this equivalent as its baked ``VIZ_CMAP``; unknown names fall back to
#: ``parula`` (MATLAB's default perceptually-uniform map).
MATLAB_CMAPS = {
    "inferno": "hot", "magma": "hot", "plasma": "hot", "hot": "hot", "afmhot": "hot",
    "viridis": "parula", "cividis": "parula", "parula": "parula",
    "gray": "gray", "grey": "gray", "gist_gray": "gray",
    "bone": "bone", "copper": "copper", "pink": "pink",
    "coolwarm": "jet", "seismic": "jet", "bwr": "jet", "rdbu": "jet", "rdbu_r": "jet",
    "jet": "jet", "turbo": "turbo", "hsv": "hsv", "cool": "cool",
    "spring": "spring", "summer": "summer", "autumn": "autumn", "winter": "winter",
}


def matlab_cmap(name: str) -> str:
    """The base-MATLAB colormap nearest to matplotlib colormap *name* (default parula)."""
    return MATLAB_CMAPS.get(str(name).strip().lower(), "parula")


PY = '''\
#!/usr/bin/env python3
# =====================================================================================
# run_viz_config.py - render the exported GottLUX visualization configuration.
# Generated by GottLUX {version} on {stamp} from '{source}'.
#
# Ported (simplified) from gottlux/core/accumulate.py (accumulate_frame) and
# gottlux/core/tonemap.py (compress / compress_signed): each rendered frame is
# accumulate -> tonemap -> colormap, exactly the view the suite displayed.
#
# Self-contained: numpy + h5py only. matplotlib OPTIONAL - the PNG frames need it;
# without it the tonemapped frames still land in viz_frames.npz. imageio OPTIONAL -
# adds the MP4 render of the whole clip; skipped (with a message) when absent.
# Run:   python run_viz_config.py [events.h5]        (default input: data.h5 here)
# Out:   viz_frame_01.png ... viz_frame_NN.png - the configured view at evenly spaced
#                                                instants (NN = N_SNAPSHOTS)
#        viz_frames.npz                        - tonemapped snapshot stack + instants
#        viz_config.mp4                        - the whole clip (only if imageio can
#                                                encode; requires imageio-ffmpeg)
# =====================================================================================
import os
import sys

import numpy as np

# ----------------------------- baked parameters (edit freely) ------------------------
VIZ_MODE       = "{viz_mode}"     # "count" (ON+OFF per pixel) or "polarity" (signed ON-OFF)
VIZ_CMAP       = "{viz_cmap}"     # any matplotlib colormap name
VIZ_TONEMAP    = "{viz_tonemap}"  # linear | sqrt | gamma | log | asinh | percentile
VIZ_GAMMA      = 0.5              # exponent for the "gamma" tone curve
CLIP_PCT       = 99.5             # white-point percentile (rejects a few hot pixels)
ACCUM_MS       = {viz_accum_ms}   # accumulation window per rendered frame (ms)
N_SNAPSHOTS    = {snap_count}     # PNG frames at evenly spaced instants
ROI            = ({roi_x0}, {roi_y0}, {roi_x1}, {roi_y1})  # (x0, y0, x1, y1) px view crop
MP4_MAX_FRAMES = 600              # cap on the number of MP4 frames

{loader}

def tone_curve(fn):
    """Apply VIZ_TONEMAP to an array already normalized to [0, 1] (tonemap._curve port)."""
    if VIZ_TONEMAP == "sqrt":
        return np.sqrt(fn)
    if VIZ_TONEMAP == "gamma":
        return np.power(fn, max(VIZ_GAMMA, 1e-3))
    if VIZ_TONEMAP == "log":
        return np.log1p(fn * 99.0) / np.log(100.0)        # ~2 decades, log(1+99x)/log(100)
    if VIZ_TONEMAP == "asinh":
        return np.arcsinh(fn * 10.0) / np.arcsinh(10.0)
    return fn                                             # linear / percentile: clip only


def tonemap(frame):
    """Non-negative frame -> display in [0, 1] (tonemap.compress: percentile white-point)."""
    pos = frame[frame > 0]
    vmax = max(float(np.percentile(pos, CLIP_PCT)), 1e-9) if pos.size else 1.0
    return tone_curve(np.clip(frame / vmax, 0.0, 1.0)).astype(np.float32)


def tonemap_signed(frame):
    """Signed frame -> display in [-1, 1] (tonemap.compress_signed: sign restored so a
    diverging colormap stays centred at zero)."""
    a = np.abs(frame)
    pos = a[a > 0]
    vmax = max(float(np.percentile(pos, CLIP_PCT)), 1e-9) if pos.size else 1.0
    return (np.sign(frame) * tone_curve(np.clip(a / vmax, 0.0, 1.0))).astype(np.float32)


def accumulate(x, y, p, H, W):
    """One (H, W) frame: per-pixel event count, or signed ON-OFF for polarity mode."""
    flat = y * W + x
    if VIZ_MODE == "polarity":
        w = np.where(p > 0, 1.0, -1.0)
        return np.bincount(flat, weights=w, minlength=H * W).reshape(H, W)
    return np.bincount(flat, minlength=H * W).astype(np.float64).reshape(H, W)


def render(frame):
    """accumulate() output -> (display array, its colormap value range)."""
    if VIZ_MODE == "polarity":
        return tonemap_signed(frame), (-1.0, 1.0)
    return tonemap(frame), (0.0, 1.0)


def get_cmap(name):
    """The named matplotlib colormap, on both the current and the pre-3.9 API."""
    import matplotlib
    try:
        return matplotlib.colormaps[name]
    except Exception:
        import matplotlib.cm as cm
        return cm.get_cmap(name)


def write_mp4(x, y, p, t_s, h, w, dt, here):
    """The whole clip as an MP4 at the accumulation cadence - only if imageio can encode
    one here (imageio + a matplotlib colormap + an ffmpeg backend); skipped otherwise."""
    try:
        import imageio.v2 as imageio
    except Exception:
        try:
            import imageio
        except Exception:
            print("imageio not available - viz_config.mp4 skipped")
            return
    try:
        cmap = get_cmap(VIZ_CMAP)
    except Exception as e:
        print("colormap %r unavailable (%s) - viz_config.mp4 skipped" % (VIZ_CMAP, e))
        return
    n = min(int(np.ceil(float(t_s[-1]) / dt)) if t_s.size else 0, MP4_MAX_FRAMES)
    if n < 1:
        print("clip shorter than one frame - viz_config.mp4 skipped")
        return
    fps = int(min(60, max(1, round(1.0 / dt))))
    out = os.path.join(here, "viz_config.mp4")
    try:
        writer = imageio.get_writer(out, fps=fps)
    except Exception as e:
        print("MP4 encoder unavailable (%s) - viz_config.mp4 skipped" % e)
        return
    try:
        for k in range(n):
            sel = (t_s >= k * dt) & (t_s < (k + 1) * dt)
            disp, lo_hi = render(accumulate(x[sel], y[sel], p[sel], h, w))
            norm = (disp - lo_hi[0]) / (lo_hi[1] - lo_hi[0])
            rgb = (np.asarray(cmap(norm))[..., :3] * 255).astype(np.uint8)
            writer.append_data(rgb)
        writer.close()
        print("wrote viz_config.mp4  (%d frames at %d fps)" % (n, fps))
    except Exception as e:
        try:
            writer.close()
        except Exception:
            pass
        print("MP4 render failed (%s) - continuing without it" % e)


def main():
    path = input_path()
    x, y, p, t_s, W, H = load_events(path)
    print("loaded %s: %d events, %dx%d px, %.3f s"
          % (os.path.basename(path), t_s.size, W, H, t_s[-1] if t_s.size else 0.0))
    if t_s.size == 0:
        print("no events - nothing to do")
        return 0

    # clamp the baked view crop to this file's geometry (a different .h5 may be smaller)
    x0 = max(0, min(ROI[0], W - 1))
    y0 = max(0, min(ROI[1], H - 1))
    x1 = max(x0 + 1, min(ROI[2], W))
    y1 = max(y0 + 1, min(ROI[3], H))
    m = (x >= x0) & (x < x1) & (y >= y0) & (y < y1)
    x, y, p, t_s = x[m] - x0, y[m] - y0, p[m], t_s[m]
    w, h = x1 - x0, y1 - y0
    print("view crop (%d,%d)-(%d,%d): %d events" % (x0, y0, x1, y1, t_s.size))
    if t_s.size == 0:
        print("no events inside the view crop - nothing to do")
        return 0

    dt = ACCUM_MS / 1000.0
    span = float(t_s[-1])
    n_snap = max(1, int(N_SNAPSHOTS))
    centers = (np.arange(n_snap) + 0.5) * (span / n_snap) if span > 0 else np.zeros(n_snap)

    here = os.path.dirname(os.path.abspath(__file__))
    plt = try_pyplot()
    stack, lo_hi = [], (0.0, 1.0)
    for k in range(n_snap):
        tc = float(centers[k])
        sel = (t_s >= tc - dt / 2.0) & (t_s < tc + dt / 2.0)
        disp, lo_hi = render(accumulate(x[sel], y[sel], p[sel], h, w))
        stack.append(disp)
        if plt is not None:
            png = os.path.join(here, "viz_frame_%02d.png" % (k + 1))
            plt.imsave(png, disp, cmap=VIZ_CMAP, vmin=lo_hi[0], vmax=lo_hi[1],
                       origin="upper")
            print("wrote %s  (t = %.3f s, %d events, %s/%s)"
                  % (os.path.basename(png), tc, int(sel.sum()), VIZ_MODE, VIZ_TONEMAP))
    if plt is None:
        print("matplotlib not available - PNG frames skipped (frames are in viz_frames.npz)")

    npz = os.path.join(here, "viz_frames.npz")
    np.savez_compressed(npz, frames=np.stack(stack), t_centers_s=centers,
                        vmin=lo_hi[0], vmax=lo_hi[1])
    print("wrote %s  (%d tonemapped %dx%d frames)" % (os.path.basename(npz), n_snap, h, w))

    write_mp4(x, y, p, t_s, h, w, dt, here)
    return 0


if __name__ == "__main__":
    sys.exit(main())
'''

M = '''\
% =====================================================================================
% run_viz_config.m - render the exported GottLUX visualization configuration.
% Generated by GottLUX {version} on {stamp} from '{source}'.
%
% Ported (simplified) from gottlux/core/accumulate.py (accumulate_frame) and
% gottlux/core/tonemap.py (compress / compress_signed): each rendered frame is
% accumulate -> tonemap -> colormap. Base MATLAB only (native h5read; R2019a+).
% Run:   open in MATLAB and press Run (or:  >> run_viz_config)
% Out:   viz_frame_01.png ... viz_frame_NN.png - the configured view at evenly spaced
%        instants (NN = N_SNAPSHOTS), plus one figure per snapshot
% =====================================================================================

% ----------------------------- baked parameters (edit freely) ------------------------
DATA_FILE   = 'data.h5';        % or set an absolute path to any GottLUX-exported .h5
VIZ_MODE    = '{viz_mode}';     % 'count' (ON+OFF per pixel) or 'polarity' (signed ON-OFF)
VIZ_CMAP    = '{viz_cmap_m}';   % base-MATLAB colormap name
VIZ_TONEMAP = '{viz_tonemap}';  % linear | sqrt | gamma | log | asinh | percentile
VIZ_GAMMA   = 0.5;              % exponent for the 'gamma' tone curve
CLIP_PCT    = 99.5;             % white-point percentile (rejects a few hot pixels)
ACCUM_MS    = {viz_accum_ms};   % accumulation window per rendered frame (ms)
N_SNAPSHOTS = {snap_count};     % PNG frames at evenly spaced instants
ROI         = [{roi_x0}, {roi_y0}, {roi_x1}, {roi_y1}];  % [x0 y0 x1 y1] px view crop

[x, y, p, t_s, W, H] = gl_load_events(DATA_FILE);
fprintf('loaded %s: %d events, %dx%d px, %.3f s\\n', DATA_FILE, numel(t_s), W, H, t_s(end));

% clamp the baked view crop to this file's geometry, then crop the events into it
x0 = max(0, min(ROI(1), W - 1));
y0 = max(0, min(ROI(2), H - 1));
x1 = max(x0 + 1, min(ROI(3), W));
y1 = max(y0 + 1, min(ROI(4), H));
m = x >= x0 & x < x1 & y >= y0 & y < y1;
x = x(m) - x0; y = y(m) - y0; p = p(m); t_s = t_s(m);
w = x1 - x0; h = y1 - y0;
fprintf('view crop (%d,%d)-(%d,%d): %d events\\n', x0, y0, x1, y1, numel(t_s));

dt = ACCUM_MS / 1000.0;
span = t_s(end);
centers = ((1:N_SNAPSHOTS) - 0.5) * (span / N_SNAPSHOTS);
for k = 1:N_SNAPSHOTS
    tc = centers(k);
    sel = t_s >= tc - dt / 2 & t_s < tc + dt / 2;
    if strcmp(VIZ_MODE, 'polarity')
        weights = 2 * p(sel) - 1;                 % ON = +1, OFF = -1
        frame = accumarray([y(sel) + 1, x(sel) + 1], weights, [h, w]);
        disp_img = sign(frame) .* gl_tonemap(abs(frame), VIZ_TONEMAP, VIZ_GAMMA, CLIP_PCT);
        lims = [-1, 1];
    else
        frame = accumarray([y(sel) + 1, x(sel) + 1], 1, [h, w]);
        disp_img = gl_tonemap(frame, VIZ_TONEMAP, VIZ_GAMMA, CLIP_PCT);
        lims = [0, 1];
    end
    fig = figure;
    imagesc(disp_img, lims);
    axis image;
    colormap(VIZ_CMAP);
    colorbar;
    title(sprintf('%s / %s, t = %.3f s (dt = %g ms)', VIZ_MODE, VIZ_TONEMAP, tc, ACCUM_MS));
    saveas(fig, sprintf('viz_frame_%02d.png', k));
end
fprintf('wrote %d viz_frame_XX.png snapshot(s)\\n', N_SNAPSHOTS);

function d = gl_tonemap(f, expr, gam, clip_pct)
% Non-negative frame -> display in [0, 1] (port of gottlux/core/tonemap.py compress):
% percentile white-point (toolbox-free sort/index), clip to [0, 1], then the tone curve.
f = double(f);
pos = sort(f(f > 0));
if isempty(pos)
    d = zeros(size(f));
    return;
end
kk = max(1, min(numel(pos), ceil(clip_pct / 100 * numel(pos))));
vmax = max(pos(kk), 1e-9);
fn = min(max(f / vmax, 0), 1);
if strcmp(expr, 'sqrt')
    d = sqrt(fn);
elseif strcmp(expr, 'gamma')
    d = fn .^ max(gam, 1e-3);
elseif strcmp(expr, 'log')
    d = log1p(fn * 99.0) / log(100.0);            % ~2 decades, log(1+99x)/log(100)
elseif strcmp(expr, 'asinh')
    d = asinh(fn * 10.0) / asinh(10.0);
else
    d = fn;                                       % linear / percentile: clip only
end
end

{loader}
'''

TOOL = ExportTool(
    name="viz_config",
    description="render the exported visualization config (mode/tonemap/colormap) as frames",
    module="gottlux/core/accumulate.py + gottlux/core/tonemap.py (accumulate → tonemap → colormap)",
    outputs=(("viz_frame_01.png … viz_frame_NN.png",
              "the configured view at evenly spaced instants (NN = the baked snap_count)"),
             ("viz_frames.npz", "the tonemapped snapshot stack + instants (Python)"),
             ("viz_config.mp4", "the whole clip at the accumulation cadence "
              "(Python, only if imageio can encode)")),
    params=(("viz_mode", "accumulation mode — 'count' (ON+OFF) or 'polarity' (signed ON−OFF)"),
            ("viz_cmap", "matplotlib colormap for the Python script"),
            ("viz_cmap_m", "nearest base-MATLAB colormap (drives the .m script)"),
            ("viz_tonemap", "tone curve before the colormap "
             "(linear|sqrt|gamma|log|asinh|percentile)"),
            ("viz_accum_ms", "accumulation window per rendered frame (ms)"),
            ("snap_count", "number of evenly spaced snapshot instants rendered to PNG"),
            ("roi_x0", "view-crop left (px)"), ("roi_y0", "view-crop top (px)"),
            ("roi_x1", "view-crop right, exclusive (px)"),
            ("roi_y1", "view-crop bottom, exclusive (px)")),
    py_template=PY,
    m_template=M,
)
