"""
file_assoc.py — make double-clicking an event recording (``.raw`` / ``.h5`` / ``.hdf5``)
open the GottLUX quick viewer (Windows + Linux).

**Windows** registers a per-user file association (``HKEY_CURRENT_USER\\Software\\Classes`` —
no admin rights needed) so Explorer routes double-clicks to :mod:`gottlux.app.quickview`.
We register one dedicated **ProgID** (``GottLUX.Recording``) with an *Open with GottLUX
viewer* verb, add it to each extension's *Open with* list, and point each extension's
default at it. Each extension's prior default is backed up so :func:`unregister` can put it
back — important for ``.h5``/``.hdf5``, which other tools (HDFView, …) may own. The launch
command uses ``pythonw.exe`` (no console window) running a tiny bootstrap
(``scripts/gottlux_view.pyw``) when running from a source checkout, or ``pythonw -m
gottlux.app.quickview`` when the package is installed.

Note on Windows 10/11: if another app already owns an extension via a hash-protected
*UserChoice*, Windows ignores the registry default we set. The association still appears
under *Open with*, and the user can pick **GottLUX viewer → Always** once to take it over —
:func:`register` says so in its returned message.

**Linux** uses the freedesktop (XDG) machinery: a shared-mime-info package
(``~/.local/share/mime/packages/gottlux-raw.xml``) declaring ``application/x-gottlux-raw``
(``*.raw``) and ``application/x-gottlux-hdf5`` (``*.h5``/``*.hdf5``), each with a
deliberately **low glob weight** (``.raw`` collides with camera photo formats and generic
``.h5`` files belong to many tools), plus a desktop entry
(``~/.local/share/applications/gottlux-view.desktop``). The mime/desktop databases are then
refreshed and the default handlers set — all best-effort ``subprocess`` calls whose absence
is reported, not raised (the written files alone are enough for most desktops after the
next login). :func:`unregister` removes both files and refreshes again.

The desktop-file / mime-XML *content* comes from the pure functions :func:`xdg_desktop_entry`
and :func:`xdg_mime_xml`, which also feed the static copies shipped in ``packaging/linux/``.
"""
from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path

PROGID = "GottLUX.Recording"
FRIENDLY = "GottLUX event recording"
EXTS = (".raw", ".h5", ".hdf5")
_CLASSES = r"Software\Classes"
_BACKUP_VALUE = "GottLUX.PrevDefault"      # + ext suffix: prior per-ext default, under our ProgID

MIME_TYPE = "application/x-gottlux-raw"
MIME_TYPE_H5 = "application/x-gottlux-hdf5"
DESKTOP_NAME = "gottlux-view.desktop"
MIME_XML_NAME = "gottlux-raw.xml"


def _is_windows() -> bool:
    return os.name == "nt"


def _pythonw() -> str:
    """The windowless interpreter next to the current one (falls back to python.exe)."""
    base = os.path.dirname(sys.executable)
    cand = os.path.join(base, "pythonw.exe")
    return cand if os.path.exists(cand) else sys.executable


def _launch_command() -> str:
    """The ``shell\\open\\command`` string: a no-console launch of the quick viewer on ``%1``."""
    pyw = _pythonw()
    launcher = Path(__file__).resolve().parents[2] / "scripts" / "gottlux_view.pyw"
    if launcher.exists():                              # running from a source checkout
        return f'"{pyw}" "{launcher}" "%1"'
    return f'"{pyw}" -m gottlux.app.quickview "%1"'    # installed package


def _icon_file():
    """The packaged multi-size ``gottlux.ico`` (generated by ``scripts/make_icons.py``), or
    ``None`` when not shipped — the ProgID's DefaultIcon is only set when it exists."""
    ico = Path(__file__).resolve().parents[2] / "packaging" / "windows" / "gottlux.ico"
    return str(ico) if ico.exists() else None


def _notify_shell():
    """Tell Explorer the association table changed so the new handler takes effect at once."""
    try:
        import ctypes
        SHCNE_ASSOCCHANGED = 0x08000000
        SHCNF_IDLIST = 0x0000
        ctypes.windll.shell32.SHChangeNotify(SHCNE_ASSOCCHANGED, SHCNF_IDLIST, None, None)
    except Exception:
        pass


# ------------------------------------------------------------------ XDG (Linux) content
def xdg_mime_xml() -> str:
    """The shared-mime-info package XML declaring the GottLUX recording mime types.

    Two types: ``application/x-gottlux-raw`` (``*.raw``) and ``application/x-gottlux-hdf5``
    (``*.h5`` / ``*.hdf5``). Every glob weight is kept **low** (40 < the 50 default) because
    ``*.raw`` also matches camera photo formats and generic ``*.h5`` files belong to many
    tools — we claim the extensions without out-shouting an existing owner.
    """
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<mime-info xmlns="http://www.freedesktop.org/standards/shared-mime-info">
  <mime-type type="{MIME_TYPE}">
    <comment>{FRIENDLY}</comment>
    <glob pattern="*.raw" weight="40"/>
  </mime-type>
  <mime-type type="{MIME_TYPE_H5}">
    <comment>{FRIENDLY} (HDF5)</comment>
    <glob pattern="*.h5" weight="40"/>
    <glob pattern="*.hdf5" weight="40"/>
  </mime-type>
</mime-info>
"""


def xdg_desktop_entry(exec_cmd: str = "gottlux-view %f") -> str:
    """The ``gottlux-view.desktop`` entry text (freedesktop Desktop Entry spec)."""
    return f"""[Desktop Entry]
Type=Application
Name=GottLUX viewer
Comment=Quick viewer for event-based-sensor (.raw / .h5 / .hdf5) recordings
Exec={exec_cmd}
Terminal=false
MimeType={MIME_TYPE};{MIME_TYPE_H5};
Categories=Science;Graphics;
"""


def _xdg_data_home() -> str:
    return os.environ.get("XDG_DATA_HOME") or os.path.join(os.path.expanduser("~"),
                                                           ".local", "share")


def _xdg_paths():
    """(mime-package XML path, desktop-entry path) under the user's XDG data home."""
    data = _xdg_data_home()
    return (os.path.join(data, "mime", "packages", MIME_XML_NAME),
            os.path.join(data, "applications", DESKTOP_NAME))


def _xdg_exec_command() -> str:
    """``gottlux-view %f`` when the console script is installed, else an explicit
    ``<python> -m gottlux.app.quickview %f`` (source checkout)."""
    import shutil
    if shutil.which("gottlux-view"):
        return "gottlux-view %f"
    return f'{sys.executable} -m gottlux.app.quickview %f'


def _run_quiet(*cmd) -> bool:
    """Run a database-refresh tool, swallowing every failure. True if it exited 0."""
    try:
        return subprocess.run(cmd, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                              timeout=30).returncode == 0
    except Exception:
        return False


def _xdg_refresh():
    """Best-effort mime/desktop database refresh; returns the names of tools that failed."""
    data = _xdg_data_home()
    failed = []
    if not _run_quiet("update-mime-database", os.path.join(data, "mime")):
        failed.append("update-mime-database")
    if not _run_quiet("update-desktop-database", os.path.join(data, "applications")):
        failed.append("update-desktop-database")
    return failed


def _register_xdg():
    mime_path, desktop_path = _xdg_paths()
    try:
        os.makedirs(os.path.dirname(mime_path), exist_ok=True)
        os.makedirs(os.path.dirname(desktop_path), exist_ok=True)
        with open(mime_path, "w", encoding="utf-8") as f:
            f.write(xdg_mime_xml())
        with open(desktop_path, "w", encoding="utf-8") as f:
            f.write(xdg_desktop_entry(_xdg_exec_command()))
    except OSError as e:
        return False, f"Could not write the XDG mime/desktop files: {e}"

    failed = _xdg_refresh()
    for mt in (MIME_TYPE, MIME_TYPE_H5):
        if not _run_quiet("xdg-mime", "default", DESKTOP_NAME, mt):
            failed.append(f"xdg-mime default ({mt})")
    msg = ("Registered: double-clicking a .raw / .h5 / .hdf5 file now offers / opens the "
           "GottLUX quick viewer.\n"
           f"  wrote: {mime_path}\n"
           f"  wrote: {desktop_path}")
    if failed:
        msg += ("\nCould not run: " + ", ".join(failed) +
                " (install shared-mime-info / desktop-file-utils / xdg-utils, or log out and "
                "back in for the desktop to pick the files up).")
    return True, msg


def _unregister_xdg():
    mime_path, desktop_path = _xdg_paths()
    for p in (mime_path, desktop_path):
        try:
            os.remove(p)
        except OSError:
            pass
    failed = _xdg_refresh()
    msg = "Unregistered: the recording mime/desktop files were removed."
    if failed:
        msg += "\nCould not run: " + ", ".join(failed) + " (databases refresh on next login)."
    return True, msg


def register():
    """Register the quick viewer as the ``.raw`` / ``.h5`` / ``.hdf5`` handler for the
    current user. Returns ``(ok: bool, message: str)``.
    """
    if not _is_windows():
        if sys.platform.startswith("linux"):
            return _register_xdg()
        return False, "File association is only supported on Windows and Linux."
    import winreg

    cmd = _launch_command()
    try:
        # --- the ProgID: name, the open verb, and the launch command ---
        with winreg.CreateKey(winreg.HKEY_CURRENT_USER, rf"{_CLASSES}\{PROGID}") as k:
            winreg.SetValueEx(k, None, 0, winreg.REG_SZ, FRIENDLY)
            winreg.SetValueEx(k, "FriendlyTypeName", 0, winreg.REG_SZ, FRIENDLY)
        with winreg.CreateKey(winreg.HKEY_CURRENT_USER,
                              rf"{_CLASSES}\{PROGID}\shell\open") as k:
            winreg.SetValueEx(k, None, 0, winreg.REG_SZ, "Open with GottLUX viewer")
        with winreg.CreateKey(winreg.HKEY_CURRENT_USER,
                              rf"{_CLASSES}\{PROGID}\shell\open\command") as k:
            winreg.SetValueEx(k, None, 0, winreg.REG_SZ, cmd)

        # --- the file-type icon: the shipped multi-size .ico, when present ---
        ico = _icon_file()
        if ico:
            with winreg.CreateKey(winreg.HKEY_CURRENT_USER,
                                  rf"{_CLASSES}\{PROGID}\DefaultIcon") as k:
                winreg.SetValueEx(k, None, 0, winreg.REG_SZ, f'"{ico}",0')

        for ext in EXTS:
            # back up the extension's existing default (once) for unregister to restore —
            # .h5/.hdf5 in particular may belong to another tool (HDFView, …)
            prev = _current_ext_default(ext)
            if prev and prev != PROGID:
                with winreg.CreateKey(winreg.HKEY_CURRENT_USER, rf"{_CLASSES}\{PROGID}") as k:
                    winreg.SetValueEx(k, _BACKUP_VALUE + ext, 0, winreg.REG_SZ, prev)

            # add to the extension's "Open with" list, and set our ProgID as its default
            with winreg.CreateKey(winreg.HKEY_CURRENT_USER,
                                  rf"{_CLASSES}\{ext}\OpenWithProgids") as k:
                winreg.SetValueEx(k, PROGID, 0, winreg.REG_NONE, b"")
            with winreg.CreateKey(winreg.HKEY_CURRENT_USER, rf"{_CLASSES}\{ext}") as k:
                winreg.SetValueEx(k, None, 0, winreg.REG_SZ, PROGID)
    except OSError as e:
        return False, f"Could not write the registry: {e}"

    _notify_shell()
    exts = " / ".join(EXTS)
    msg = (f"Registered: double-clicking a {exts} file now opens the GottLUX quick viewer.\n"
           f"  launch: {cmd}\n"
           "If Windows still opens another app (a locked default association), right-click the "
           "file → Open with → Choose another app → 'GottLUX viewer' → check 'Always'.")
    return True, msg


def unregister():
    """Remove the associations and restore each extension's previous default.
    Returns ``(ok, msg)``."""
    if not _is_windows():
        if sys.platform.startswith("linux"):
            return _unregister_xdg()
        return False, "File association is only supported on Windows and Linux."
    import winreg

    for ext in EXTS:
        prev = _read_value(rf"{_CLASSES}\{PROGID}", _BACKUP_VALUE + ext)
        if prev is None and ext == ".raw":            # pre-1.0 builds used an unsuffixed backup
            prev = _read_value(rf"{_CLASSES}\{PROGID}", _BACKUP_VALUE)
        # restore (or clear) the extension default only if it still points at us
        if _current_ext_default(ext) == PROGID:
            try:
                with winreg.CreateKey(winreg.HKEY_CURRENT_USER, rf"{_CLASSES}\{ext}") as k:
                    if prev:
                        winreg.SetValueEx(k, None, 0, winreg.REG_SZ, prev)
                    else:
                        winreg.DeleteValue(k, "")
            except OSError:
                pass
        # drop our entry from the "Open with" list
        try:
            with winreg.OpenKey(winreg.HKEY_CURRENT_USER, rf"{_CLASSES}\{ext}\OpenWithProgids",
                                0, winreg.KEY_SET_VALUE) as k:
                winreg.DeleteValue(k, PROGID)
        except OSError:
            pass
    # delete the whole ProgID tree
    _delete_tree(rf"{_CLASSES}\{PROGID}")

    _notify_shell()
    return True, ("Unregistered: the " + " / ".join(EXTS) +
                  " associations were removed and the previous defaults restored.")


# --------------------------------------------------------------------- helpers
def _current_ext_default(ext):
    return _read_value(rf"{_CLASSES}\{ext}", None)


def _read_value(subkey, name):
    """Read a string value (``name=None`` for the default), or ``None`` if absent."""
    import winreg
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, subkey) as k:
            val, _ = winreg.QueryValueEx(k, name)
            return val or None
    except OSError:
        return None


def _delete_tree(subkey):
    """Recursively delete a registry key and its subkeys under HKCU."""
    import winreg
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, subkey, 0,
                            winreg.KEY_READ | winreg.KEY_WRITE) as k:
            while True:
                try:
                    child = winreg.EnumKey(k, 0)
                except OSError:
                    break
                _delete_tree(f"{subkey}\\{child}")
        winreg.DeleteKey(winreg.HKEY_CURRENT_USER, subkey)
    except OSError:
        pass
