"""
resolution_report.py — paper-ready export of a pixels-on-target / perception-range study.

:func:`save_resolution_study` writes a self-contained, reproducible bundle (figures as raster +
vector, tables as Parquet + CSV, a machine-readable JSON summary, and a Markdown methods/results
report) for a :class:`~gottlux.core.photogrammetry.ResolutionStudy`. It is used by the Range-lab
GUI's Export button and is equally callable headless.
"""
from __future__ import annotations

import os

from gottlux.io import export


def _datasheet_md(profile) -> list:
    """Markdown rows for the capture rig's sensor + camera datasheet (provenance)."""
    lines = ["## Capture rig (sensor + camera)", ""]
    for section, rows in profile.datasheet().items():
        lines += [f"**{section}**", "", "| field | value |", "|---|---|"]
        lines += [f"| {label} | {value} |" for label, value in rows if value != ""]
        lines.append("")
    return lines


def _report_md(study, summary, profile=None) -> str:
    inp = summary["inputs"]
    fit = summary["fit"]
    L = summary["size_used_for_ranges_m"]
    lines = [
        f"# Pixels-on-target & perception-range study",
        "",
    ]
    if profile is not None:
        lines += _datasheet_md(profile)
    lines += [
        "## Method",
        "Pinhole projection of a target's critical dimension onto the sensor:",
        "",
        "```",
        "f_px = (W/2) / tan(FOV/2)          focal length in pixels",
        "N(D) = L · f_px / D                pixels on target at range D",
        "D(N) = L · f_px / N                range at which the target spans N pixels",
        "IFOV = FOV / W                     per-pixel angular resolution",
        "GSD(D) = D · IFOV                  metres per pixel at range D",
        "```",
        "",
        "Perception thresholds use **Johnson's criteria** (cycles across the critical dimension, "
        "2 px per resolved cycle): detection 1.0 cyc (2 px), orientation 1.4 (2.8 px), "
        "recognition 4.0 (8 px), identification 6.4 (12.8 px).",
        "",
        "## Inputs",
        f"- Target critical size **L = {inp['target_size_m']} m**",
        f"- Horizontal FOV **{inp['fov_deg']}°** across **W = {inp['width_px']} px** "
        f"(H = {inp['height_px']} px)",
        f"- Focal length **f = {inp['focal_px']} px**, IFOV **{inp['ifov_mrad']} mrad/px**",
        "",
    ]
    if fit.get("n", 0):
        lines += [
            "## Empirical target-size fit (from ranged keyframes)",
            f"- keyframes with known range: **{fit['n']}**",
            f"- least-squares effective size **L_fit = {fit.get('fitted_target_size_m')} m** "
            f"(implied size {fit.get('implied_size_mean_m')} ± {fit.get('implied_size_std_m')} m"
            + (f", R² = {fit['r2']}" if fit.get("r2") is not None else "") + ")",
            f"- size used for the range table below: **{L} m**",
            "",
        ]
    lines += ["## Perception ranges (max range for each task)", "",
              "| task | pixels across | max range (m) |", "|---|---:|---:|"]
    jp = summary["johnson_pixels"]
    for task, dr in summary["perception_ranges_m"].items():
        lines.append(f"| {task} | {jp[task]:g} | {dr:.1f} |")
    lines += ["", "## Keyframes", "",
              "| t (s) | label | box w×h (px) | meas. px | range (m) | expected px | "
              "implied size (m) | GSD (m/px) |", "|---:|---|---|---:|---:|---:|---:|---:|"]
    for k in summary["keyframes"]:
        lines.append(
            f"| {k['t_s']:.3f} | {k.get('label','')} | "
            f"{k['width_px']:.0f}×{k['height_px']:.0f} | {k['measured_px_on_target']:.1f} | "
            f"{'' if k['distance_m'] is None else f'{k['distance_m']:.1f}'} | "
            f"{k.get('expected_px_on_target','')} | {k.get('implied_target_size_m','')} | "
            f"{k.get('gsd_m_per_px','')} |")
    lines += ["", "_Generated by GottLUX (gottlux.run.resolution_report)._", ""]
    return "\n".join(lines)


def save_resolution_study(out_base, study, title=None, dpi=300, profile=None) -> list:
    """Write the full paper-ready bundle for *study* at ``out_base`` (a path stem).

    Products: ``*_pixels_on_target.{png,pdf}`` (figure), ``*_keyframes.{parquet,csv}`` (raw),
    ``*_resolution_solved.{parquet,csv}`` (derived), ``*_resolution.json`` (summary), and
    ``*_resolution_report.md`` (methods + results). Returns every path written.

    *profile* is the capture rig (a :class:`gottlux.sensors.SensorProfile`); when given, its
    sensor/camera datasheet is recorded in both the JSON summary and the Markdown report for
    provenance. Defaults to the active default rig.
    """
    if profile is None:
        from gottlux import sensors
        profile = sensors.get(sensors.DEFAULT_PROFILE)
    base = os.path.splitext(out_base)[0]
    os.makedirs(os.path.dirname(os.path.abspath(base)) or ".", exist_ok=True)
    summary = study.summary()
    summary["sensor_profile"] = profile.to_dict()
    written = []

    # 1) the publication figure (raster + vector)
    try:
        import matplotlib
        matplotlib.use("Agg")
        from gottlux.viz.resolution import pixels_on_target_figure
        fig = pixels_on_target_figure(study, size_used_m=summary["size_used_for_ranges_m"],
                                      title=title)
        written += export.save_figure(fig, base + "_pixels_on_target", dpi=dpi,
                                      formats=("png", "pdf"), close=True,
                                      metadata={"title": "pixels on target vs range"})
    except Exception as e:   # never let a plotting hiccup lose the tables
        print(f"[gottlux] resolution figure failed: {e}")

    # 2) raw keyframes table
    kf_rows = {k: [] for k in ("t_s", "label", "x0", "y0", "x1", "y1", "distance_m")}
    for k in study.keyframes:
        kf_rows["t_s"].append(round(float(k.t_s), 4)); kf_rows["label"].append(k.label)
        kf_rows["x0"].append(k.bbox[0]); kf_rows["y0"].append(k.bbox[1])
        kf_rows["x1"].append(k.bbox[2]); kf_rows["y1"].append(k.bbox[3])
        kf_rows["distance_m"].append("" if k.distance_m is None else k.distance_m)
    written += export.save_table(kf_rows, base + "_keyframes")

    # 3) solved per-keyframe table
    solved = study.solved()
    if solved:
        cols = sorted({c for row in solved for c in row})
        tbl = {c: [row.get(c, "") for row in solved] for c in cols}
        written += export.save_table(tbl, base + "_resolution_solved")

    # 4) machine-readable summary + 5) the methods/results report
    written += export.save_json(summary, base + "_resolution.json")
    md_path = base + "_resolution_report.md"
    with open(md_path, "w", encoding="utf-8") as f:
        f.write(_report_md(study, summary, profile=profile))
    written.append(md_path)
    return written
